/* WaylandReaper — standalone force-close extension for GNOME Shell (Wayland)
 *
 * ══════════════════════════════════════════════════════════════════
 *  ⚠️⚠️⚠️  AI GENERATED CODE  ⚠️⚠️⚠️
 *  Generated by an AI assistant (Monika / Hermes Agent) at the
 *  request of Nastya Grifon. Review before production use.
 * ══════════════════════════════════════════════════════════════════
 *
 * Copyright (C) 2026 Nastya Grifon (nastyagrifon.me)
 *
 * Replaces the old script + third-party-extension combo: this extension is
 * fully self-contained. Binds a configurable hotkey, resolves the focused
 * window via Meta, and terminates its process (SIGTERM → grace → SIGKILL).
 *
 * Relevant parts adapted from:
 *   hseliger/window-calls-extended          — original concept, GPL-2.0-or-later
 *   dev-muhammad-adel/window-calls-extended — maximized-flag rebuild for 49+
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import Meta from 'gi://Meta';
import Shell from 'gi://Shell';
import * as Main from 'resource:///org/gnome/shell/ui/main.js';
import {Extension} from 'resource:///org/gnome/shell/extensions/extension.js';

export default class WaylandReaperExtension extends Extension {
    enable() {
        this._graceSources = new Map(); // pid -> pending SIGKILL source id
        this._settings = this.getSettings();
        // Canonical pattern from caffeine on THIS shell: Main.wm.addKeybinding,
        // own settings object, Shell.ActionMode.ALL. Two slots: both bound to
        // the same callback; empty strv = slot disabled (shell skips it).
        for (const key of ['kill-focused-window', 'kill-focused-window-alt'])
            Main.wm.addKeybinding(
                key,
                this._settings,
                Meta.KeyBindingFlags.IGNORE_AUTOREPEAT,
                Shell.ActionMode.ALL,
                () => this._reapFocusedWindow()
            );
    }

    disable() {
        for (const key of ['kill-focused-window', 'kill-focused-window-alt'])
            Main.wm.removeKeybinding(key);
        this._clearGrace();
    }

    _clearGrace(pid = null) {
        if (pid !== null) {
            const id = this._graceSources.get(pid);
            if (id) {
                GLib.source_remove(id);
                this._graceSources.delete(pid);
            }
            return;
        }
        for (const id of this._graceSources.values())
            GLib.source_remove(id);
        this._graceSources.clear();
    }

    _notify(title, body) {
        // Kill notifications are opt-in (show-notifications, default off).
        // Errors still go to the journal regardless of the toggle.
        if (!this._settings.get_boolean('show-notifications'))
            return;
        try {
            Main.notify(title, body);
        } catch (e) {
            console.warn(`${this.metadata.name}: notify failed: ${e}`);
        }
    }

    _notifyError(body) {
        try {
            Main.notify('WaylandReaper', body);
        } catch (e) {
            console.warn(`${this.metadata.name}: notify failed: ${e}`);
        }
    }

    _commOf(pid) {
        // /proc/<pid>/comm = process name (same as `ps -o comm=`)
        const path = `/proc/${pid}/comm`;
        try {
            const [ok, bytes] = GLib.file_get_contents(path);
            return ok ? String.fromCharCode(...bytes).trim().replace(/\0/g, '') : '';
        } catch (e) {
            return '';
        }
    }

    _reapFocusedWindow() {
        const win = global.display.get_focus_window();

        // Empty desktop: nothing to do, stay silent
        if (!win) {
            this._notifyError('Нет сфокусированного окна.');
            return;
        }

        const pid = win.get_pid();
        const title = win.get_title() || '(untitled)';
        const wmClass = win.get_wm_class() || 'unknown';

        if (!pid || pid <= 2) {
            this._notifyError(`Не удалось определить PID окна «${title}».`);
            return;
        }

        // Whitelist check — exact comm match
        const comm = this._commOf(pid);
        const whitelist = this._settings.get_strv('whitelist');
        if (whitelist.includes(comm)) {
            this._notify('WaylandReaper',
                `«${title}» (${comm}) в whitelist — не трогаю.`);
            return;
        }
        // SIGTERM first
        try {
            GLib.spawn_command_line_sync(`kill ${pid}`);
        } catch (e) {
            this._notifyError(`kill ${pid}: ${e.message}`);
            return;
        }

        // Grace period, then SIGKILL if STILL ALIVE (checked, not blind)
        const graceMs = this._settings.get_int('grace-period-ms');
        this._clearGrace(pid); // re-press on same window: restart its grace
        const sourceId = GLib.timeout_add_once(GLib.PRIORITY_DEFAULT,
            Math.max(graceMs, 100), () => {
                this._graceSources.delete(pid);
                try {
                    // /proc/<pid> gone = process already exited from TERM
                    const [alive] = GLib.spawn_command_line_sync(
                        `sh -c 'test -d /proc/${pid} && echo a'`);
                    const out = alive ? alive.get_data_as_string().trim() : '';
                    if (out === 'a') {
                        GLib.spawn_command_line_sync(`kill -9 ${pid}`);
                        console.info(`${this.metadata.name}: SIGKILL ${pid}`);
                    }
                } catch (e) {
                    console.warn(`${this.metadata.name}: kill -9 check failed: ${e}`);
                }
            });
        this._graceSources.set(pid, sourceId);

        this._notify('WaylandReaper',
            `Закрываю «${title}» (${wmClass}, PID ${pid}).`);
    }
}
